[package]
name = "rustmc-players"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
async-trait = "0.1.74"
tokio = { version = "1.34.0", features = ["full"] }
rustmc-server = { path = "../rustmc-server" }
