[package]
name = "rustmc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
tokio = { version = "1.34.0", features = ["full"] }

rustmc-packets = { path = "../rustmc-packets" }
rustmc-errors = { path = "../rustmc-errors" }
